import React from 'react';
import { Link } from 'react-router-dom';
import { Card } from '@/components/ui/card';
import { Sparkles, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-surface text-foreground">
      <div className="container mx-auto px-4 sm:px-6 py-12">
        <Card className="card-premium p-6 sm:p-8 md:p-12 border border-border/50 max-w-3xl mx-auto">
          <div className="text-center mb-10">
            <div className="inline-block p-3 bg-gradient-primary rounded-xl glow-primary mb-4">
              <Sparkles className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-gradient">Terms of Service</h1>
            <p className="text-muted-foreground mt-2">Last Updated: July 25, 2025</p>
          </div>

          <div className="space-y-6 text-left">
            <p className="text-muted-foreground">Welcome to Premio! These Terms of Service ("Terms") govern your use of our SEO and AI-powered toolkit ("Services"). By accessing or using our Services, you agree to be bound by these Terms.</p>
            
            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">1. Account Registration</h3>
              <p className="text-muted-foreground">You must register for an account to access our Services. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for all activities that occur under your account.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">2. Use of Services</h3>
              <p className="text-muted-foreground">Our Services provide tools for AI content humanization, SEO article generation, keyword research, and more. You agree to use these tools responsibly and in compliance with all applicable laws. You are solely responsible for the content you create, input, or manage using our Services.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">3. User-Generated Content</h3>
              <p className="text-muted-foreground">You retain all rights to the content you generate ("User Content"). By using the Services, you grant Premio a worldwide, non-exclusive, royalty-free license to use, reproduce, and display the User Content solely for the purpose of operating and providing the Services to you.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">4. Prohibited Activities</h3>
              <p className="text-muted-foreground">You agree not to engage in any of the following prohibited activities: (i) using the Services for any illegal purpose or in violation of any local, state, national, or international law; (ii) creating content that is defamatory, obscene, or otherwise objectionable; (iii) attempting to interfere with the proper functioning of the Service.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">5. Disclaimers</h3>
              <p className="text-muted-foreground">The AI-generated content is provided for informational purposes only. While we strive for accuracy, Premio does not guarantee the correctness, completeness, or reliability of any content generated by the AI. You should independently verify any information before relying on it.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">6. Termination</h3>
              <p className="text-muted-foreground">We may terminate or suspend your account and bar access to the Services immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-semibold text-primary">7. Contact Us</h3>
              <p className="text-muted-foreground">If you have any questions about these Terms, please contact us at <a href="mailto:support@premio.ai" className="text-primary/90 hover:underline">support@premio.ai</a>.</p>
            </div>
          </div>
        </Card>

        <div className="text-center mt-12">
          <Button asChild variant="outline" className="bg-transparent hover:bg-white/5">
            <Link to="/login">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Return to Login
            </Link>
          </Button>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
